version: 2

models:

  - name: dim__listings
    description: "{{ doc('dim__listings_doc') }}"
    columns:
      - name: listing_id
        tests:
          - unique
          - not_null

      - name: price
        tests:
          - positive_value


  - name: fct__reviews
    description: "{{ doc('fct__reviews_doc') }}"
    columns:
      - name: reviewer_id
        tests:
          - not_null

      - name: listing_id
        tests:
          - relationships:
              to: ref('dim__listings')
              field: listing_id


  - name: agg__guest_stats
    description: "{{ doc('agg__guest_stats_doc') }}"
    columns:
      - name: reviewer_id
        tests:
          - unique
          - not_null

      - name: price_per_night
        tests:
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn